# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('tag_name', models.CharField(max_length=120)),
                ('audio_file_name', models.FileField(upload_to='audio/%Y/%m/%d')),
            ],
        ),
    ]
